import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";


// font optimization-------------------------------------
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${roboto.className} antialiased`}
      >
        {children}
        {modal}
      </body>
    </html>
  );
}
